apiVersion: v2
name: selenium-grid
description: A Helm chart for creating a Selenium Grid Server in Kubernetes
type: application
version: 0.42.1
appVersion: 4.31.0-20250414
icon: https://github.com/SeleniumHQ/docker-selenium/raw/trunk/logo.png
dependencies:
- repository: https://kedacore.github.io/charts
  version: 2.17.0
  name: keda
  condition: autoscaling.enabled, keda.enabled
- repository: https://kubernetes.github.io/ingress-nginx
  version: 4.12.1
  name: ingress-nginx
  condition: ingress.enableWithController, ingress-nginx.enabled
- repository: https://jaegertracing.github.io/helm-charts
  version: 3.4.1
  name: jaeger
  condition: tracing.enabled, jaeger.enabled
- repository: https://prometheus-community.github.io/helm-charts
  version: 70.4.2
  name: kube-prometheus-stack
  condition: monitoring.enabled, kube-prometheus-stack.enabled
- repository: https://charts.bitnami.com/bitnami
  version: 16.6.3
  name: postgresql
  condition: postgresql.enabled
- repository: https://charts.bitnami.com/bitnami
  version: 20.12.0
  name: redis
  condition: redis.enabled
maintainers:
  - name: SeleniumHQ
    email: docker-selenium@seleniumhq.org
    url: https://github.com/SeleniumHQ
sources:
  - https://github.com/SeleniumHQ/docker-selenium
