# To execute this docker compose yml file use `docker compose -f docker-compose-v3-dev.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker compose -f docker-compose-v3-dev.yml down`
services:
  chrome:
    image: selenium/node-chrome:4.33.0-20250525
    platform: linux/amd64
    shm_size: 2gb
    volumes:
      - ./selenium_server_deploy.jar:/opt/selenium/selenium-server.jar
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub

  edge:
    image: selenium/node-edge:4.33.0-20250525
    platform: linux/amd64
    shm_size: 2gb
    volumes:
      - ./selenium_server_deploy.jar:/opt/selenium/selenium-server.jar
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub

  firefox:
    image: selenium/node-firefox:4.33.0-20250525
    shm_size: 2gb
    volumes:
      - ./selenium_server_deploy.jar:/opt/selenium/selenium-server.jar
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub

  selenium-hub:
    image: selenium/hub:4.33.0-20250525
    container_name: selenium-hub
    volumes:
      - ./selenium_server_deploy.jar:/opt/selenium/selenium-server.jar
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
